// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: definition/mygrpc.proto

package definition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_definition_mygrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_definition_mygrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_definition_mygrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Student) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type StudentRequestById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentRequestById) Reset() {
	*x = StudentRequestById{}
	mi := &file_definition_mygrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentRequestById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentRequestById) ProtoMessage() {}

func (x *StudentRequestById) ProtoReflect() protoreflect.Message {
	mi := &file_definition_mygrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentRequestById.ProtoReflect.Descriptor instead.
func (*StudentRequestById) Descriptor() ([]byte, []int) {
	return file_definition_mygrpc_proto_rawDescGZIP(), []int{1}
}

func (x *StudentRequestById) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_definition_mygrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_definition_mygrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_definition_mygrpc_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_definition_mygrpc_proto protoreflect.FileDescriptor

const file_definition_mygrpc_proto_rawDesc = "" +
	"\n" +
	"\x17definition/mygrpc.proto\x12\atrygrpc\x1a\x1bgoogle/protobuf/empty.proto\"W\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\"$\n" +
	"\x12StudentRequestById\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"3\n" +
	"\x05Error\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xc5\x02\n" +
	"\x0eStudentService\x12.\n" +
	"\n" +
	"AddStudent\x12\x10.trygrpc.Student\x1a\x0e.trygrpc.Error\x12@\n" +
	"\x0fDescribeStudent\x12\x1b.trygrpc.StudentRequestById\x1a\x10.trygrpc.Student\x12:\n" +
	"\fListStudents\x12\x16.google.protobuf.Empty\x1a\x10.trygrpc.Student0\x01\x127\n" +
	"\x11AddSeveralStudent\x12\x10.trygrpc.Student\x1a\x0e.trygrpc.Error(\x01\x12L\n" +
	"\x17DescribeSeveralStudents\x12\x1b.trygrpc.StudentRequestById\x1a\x10.trygrpc.Student(\x010\x01B1Z/github.com/qs-lzh/trygrpc/definition;definitionb\x06proto3"

var (
	file_definition_mygrpc_proto_rawDescOnce sync.Once
	file_definition_mygrpc_proto_rawDescData []byte
)

func file_definition_mygrpc_proto_rawDescGZIP() []byte {
	file_definition_mygrpc_proto_rawDescOnce.Do(func() {
		file_definition_mygrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_definition_mygrpc_proto_rawDesc), len(file_definition_mygrpc_proto_rawDesc)))
	})
	return file_definition_mygrpc_proto_rawDescData
}

var file_definition_mygrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_definition_mygrpc_proto_goTypes = []any{
	(*Student)(nil),            // 0: trygrpc.Student
	(*StudentRequestById)(nil), // 1: trygrpc.StudentRequestById
	(*Error)(nil),              // 2: trygrpc.Error
	(*emptypb.Empty)(nil),      // 3: google.protobuf.Empty
}
var file_definition_mygrpc_proto_depIdxs = []int32{
	0, // 0: trygrpc.StudentService.AddStudent:input_type -> trygrpc.Student
	1, // 1: trygrpc.StudentService.DescribeStudent:input_type -> trygrpc.StudentRequestById
	3, // 2: trygrpc.StudentService.ListStudents:input_type -> google.protobuf.Empty
	0, // 3: trygrpc.StudentService.AddSeveralStudent:input_type -> trygrpc.Student
	1, // 4: trygrpc.StudentService.DescribeSeveralStudents:input_type -> trygrpc.StudentRequestById
	2, // 5: trygrpc.StudentService.AddStudent:output_type -> trygrpc.Error
	0, // 6: trygrpc.StudentService.DescribeStudent:output_type -> trygrpc.Student
	0, // 7: trygrpc.StudentService.ListStudents:output_type -> trygrpc.Student
	2, // 8: trygrpc.StudentService.AddSeveralStudent:output_type -> trygrpc.Error
	0, // 9: trygrpc.StudentService.DescribeSeveralStudents:output_type -> trygrpc.Student
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_definition_mygrpc_proto_init() }
func file_definition_mygrpc_proto_init() {
	if File_definition_mygrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_definition_mygrpc_proto_rawDesc), len(file_definition_mygrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_definition_mygrpc_proto_goTypes,
		DependencyIndexes: file_definition_mygrpc_proto_depIdxs,
		MessageInfos:      file_definition_mygrpc_proto_msgTypes,
	}.Build()
	File_definition_mygrpc_proto = out.File
	file_definition_mygrpc_proto_goTypes = nil
	file_definition_mygrpc_proto_depIdxs = nil
}
